machine:
  node:
    version: 0.11.8
checkout:
  post:
    - git submodule sync
    - git submodule update --init
database:
  override:
    - mysql -u ubuntu circle_test < my-database-setup.sql
test:
  override:
    - php ./test-suite/run.php --unit-tests
test:
  override:
    - php ./app/run-server.php --daemon
    - php ./test-suite/run.php --unit-tests
